DEBUG 2025-06-11 06:36:26.414 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-11 06:36:26.414 UTC: 	 Running on: Linux lxplus968.cern.ch 5.14.0-503.35.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 24 11:15:27 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-11 06:36:26.414 UTC: 	 Not using Singularity
DEBUG 2025-06-11 06:36:26.414 UTC: 	 Operating System: Red Hat Enterprise Linux 9.6 (Plow)
DEBUG 2025-06-11 06:36:26.414 UTC: 	 Executing command: 'status'
DEBUG 2025-06-11 06:36:26.414 UTC: 	 Found CRAB cache file /afs/cern.ch/user/z/zhipeng/.crab3
ERROR 2025-06-11 06:36:26.415 UTC: 	 Error: crab_MINIAOD_2022M5_TnP_v2 is not a valid CRAB project directory.
ERROR 2025-06-11 06:36:26.415 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_MINIAOD_2022M5_TnP_v2 is not a valid CRAB project directory.
INFO 2025-06-11 06:36:26.420 UTC: 	 Log file is /eos/home-z/zhipeng/A_Jpsi_Cross_Section/TnP_Single_Muon_Eff/CMSSW_13_0_13/src/MuonAnalysis/MuonAnalyzer/test/mycrab_2022/crab.log
DEBUG 2025-06-11 07:03:39.116 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-11 07:03:39.117 UTC: 	 Running on: Linux lxplus968.cern.ch 5.14.0-503.35.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Mar 24 11:15:27 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-11 07:03:39.117 UTC: 	 Not using Singularity
DEBUG 2025-06-11 07:03:39.117 UTC: 	 Operating System: Red Hat Enterprise Linux 9.6 (Plow)
DEBUG 2025-06-11 07:03:39.117 UTC: 	 Executing command: 'status'
DEBUG 2025-06-11 07:03:39.117 UTC: 	 Found CRAB cache file /afs/cern.ch/user/z/zhipeng/.crab3
ERROR 2025-06-11 07:03:39.117 UTC: 	 Error: ./crab_MINIAOD_2022M6_TnP_v2 is not a valid CRAB project directory.
ERROR 2025-06-11 07:03:39.118 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: ./crab_MINIAOD_2022M6_TnP_v2 is not a valid CRAB project directory.
INFO 2025-06-11 07:03:39.121 UTC: 	 Log file is /eos/home-z/zhipeng/A_Jpsi_Cross_Section/TnP_Single_Muon_Eff/CMSSW_13_0_13/src/MuonAnalysis/MuonAnalyzer/test/mycrab_2022/crab.log
DEBUG 2025-06-14 10:14:44.177 UTC: 	 CRAB Client version: v3.250409
DEBUG 2025-06-14 10:14:44.177 UTC: 	 Running on: Linux lxplus959.cern.ch 5.14.0-570.18.1.el9_6.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 20 07:50:24 EDT 2025 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-06-14 10:14:44.177 UTC: 	 Not using Singularity
DEBUG 2025-06-14 10:14:44.177 UTC: 	 Operating System: Red Hat Enterprise Linux 9.6 (Plow)
DEBUG 2025-06-14 10:14:44.177 UTC: 	 Executing command: 'status'
DEBUG 2025-06-14 10:14:44.177 UTC: 	 Found CRAB cache file /afs/cern.ch/user/z/zhipeng/.crab3
ERROR 2025-06-14 10:14:44.178 UTC: 	 Error: crab_MINIAOD_2022M2_TnP_v3 is not a valid CRAB project directory.
ERROR 2025-06-14 10:14:44.178 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/status.py", line 48, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 281, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.250409.00/lib/CRABClient/Commands/SubCommand.py", line 691, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_MINIAOD_2022M2_TnP_v3 is not a valid CRAB project directory.
INFO 2025-06-14 10:14:44.182 UTC: 	 Log file is /eos/home-z/zhipeng/A_Jpsi_Cross_Section/TnP_Single_Muon_Eff/CMSSW_13_0_13/src/MuonAnalysis/MuonAnalyzer/test/mycrab_2022/crab.log
